all:
  children:
    prodgeek:
      hosts:
        10.100.10.21:
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/ansible_key
          ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
          php_webserver_daemon: "nginx"
          php_default_version_debian: "7.4"